[app]
name = "AyoLesCore"
version = "0.0.1"
host = "localhost"
port = 80
read_timeout = 5
write_timeout = 10
idle_timeout = 15
temp = "/template/*.gohtml"

[database]
host = "ec2-174-129-33-207.compute-1.amazonaws.com"
port = 5432
name = "d7adv67i235u7r"
sslmode = "disable"
username = "csaqiwvemuknps"
password = "a4a89a3cd073e0f2f11959e7a307029e426d55bf5a04e93b9d9eaf84d320c2f7"

[sql]
schema = "/sql/ayoles_db_pq.sql"
seed = "/sql/seed.sql"