[app]
name = "AyoLesCore"
version = "0.0.1"
host = "localhost"
port = 8000
read_timeout = 5
write_timeout = 10
idle_timeout = 15

[database]
host = "localhost"
port = 26257
name = "ayoles_db"
sslmode = "disable"
username = "root"
password = ""

[sql]
schema = "/sql/ayoles_db.sql"
seed = "/sql/seed.sql"